version: '3.4'
services:
  agi_perception:
    container_name: agi_perception
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    command: tail -f /dev/null
    volumes:
      - ../agi_perception:/app/agi_perception
      - ../README.md:/app/README.md
      - ../pyproject.toml:/app/pyproject.toml
    # command: poetry run python /app/agi_perception/segmentate_image.py
    working_dir: /app
